scene_name = 'asdf'

[camera]
aspect_ratio = 1.7777777910232544
far_plane = 100.0
fov = 45.0
front = [ 0.0, 0.0, -1.0 ]
name = 'main'
near_plane = 0.10000000149011612
pitch = 0.0
position = [ 0.0, 0.5, 3.0 ]
up = [ 0.0, 0.25, 0.0 ]
yaw = -90.0

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'pointLight_visual'

    [entity.material]
    name = 'pointLight_material'

        [entity.material.properties]
        color = [ 2.0, 2.0, 2.0 ]
        useTexture = 0

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'default'
    path = '../Assets/Textures/default.png'

    [entity.transform]
    position = [ 0.0, 2.0, 0.0 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 0.20000000298023224, 0.20000000298023224, 0.20000000298023224 ]

[[entity]]
color = [ 0.5, 0.5, 0.5, 0.5 ]
is_active = true
mesh = 'plane'
name = 'floor'

    [entity.material]
    name = 'default'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 0

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'default'
    path = '../Assets/Textures/default.png'

    [entity.transform]
    position = [ 0.0, 0.0, 0.0 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 100.0, 1.0, 100.0 ]

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'cube1'

    [entity.material]
    name = 'container1'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 1

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'container'
    path = '../Assets/Textures/container.png'

    [entity.transform]
    position = [ 3.0, 0.5, 0.0 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'cube2'

    [entity.material]
    name = 'container2'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 1

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'container'
    path = '../Assets/Textures/container.png'

    [entity.transform]
    position = [ 0.9270509481430054, 0.5, 2.8531696796417236 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'cube3'

    [entity.material]
    name = 'container3'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 1

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'container'
    path = '../Assets/Textures/container.png'

    [entity.transform]
    position = [ -2.427051067352295, 0.5, 1.7633554935455322 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'cube4'

    [entity.material]
    name = 'container4'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 1

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'container'
    path = '../Assets/Textures/container.png'

    [entity.transform]
    position = [ -2.427050828933716, 0.5, -1.76335608959198 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[[entity]]
color = [ 1.0, 1.0, 1.0, 1.0 ]
is_active = true
mesh = 'cube'
name = 'cube5'

    [entity.material]
    name = 'container5'

        [entity.material.properties]
        ambientColor = [ 0.10000000149011612, 0.10000000149011612, 0.10000000149011612 ]
        ambientStrength = 0.10000000149011612
        color = [ 1.0, 1.0, 1.0 ]
        diffuseStrength = 0.699999988079071
        isEmissive = 0
        mainTexture = 0
        shininess = 32.0
        specularStrength = 0.5
        useTexture = 1

        [entity.material.shader]
        fragment_path = '../src/Shaders/default.frag'
        is_valid = true
        name = 'default'
        vertex_path = '../src/Shaders/default.vert'

    [entity.texture]
    is_valid = true
    name = 'container'
    path = '../Assets/Textures/container.png'

    [entity.transform]
    position = [ 0.9270513653755188, 0.5, -2.8531694412231445 ]
    rotation = [ 0.0, 0.0, 0.0 ]
    scale = [ 1.0, 1.0, 1.0 ]

[[light]]
color = [ 1.0, 1.0, 1.0 ]
intensity = 3.0
is_active = true
name = 'pointLight'
position = [ 0.0, 2.0, 0.0 ]
type = 'point'